// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log("Di Remedial biar Lumayan");

console.log("Hayu kita Remedial");

console.log("Mending kalau Nilainya Bagus ");

var pesan = "Pagi-pagi Malas Mandi";

console.log(pesan);

var greeting = "Wilujeung Tepang";

var nilai = 45;

var nilaiRemed = 60;

exports.greeting = greeting;
exports.nilai = nilai;
exports.nilaiRemed = nilaiRemed;
exports.pesan = pesan;
/*  Not a pure module */
