// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello");

console.log("x");

console.log(23);

console.log(-23);

console.log(23.0);

console.log(-23.0);

console.log(24);

console.log(23.0 + 2.0);

console.log(0);

console.log(2.0 / 23.0 * 1.0);

console.log(Math.pow(2.0, 2.0));

console.log("Hello World");

/*  Not a pure module */
