// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var multilineGreeting = "Hello\n    world";

var oneSlash = "\\";

var greeting = "Hello world!";

exports.multilineGreeting = multilineGreeting;
exports.oneSlash = oneSlash;
exports.greeting = greeting;
/* No side effect */
