// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var ageAndName = /* tuple */[
  24,
  "Lil' Reason"
];

var my3dCoordinates = /* tuple */[
  20.0,
  30.5,
  100.0
];

var y = 30.5;

exports.ageAndName = ageAndName;
exports.my3dCoordinates = my3dCoordinates;
exports.y = y;
/* No side effect */
