// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log(10);

console.log(10);

function add(x, y) {
  return x + y | 0;
}

var score = 10;

var myInt = 9;

var x = 10;

exports.score = score;
exports.myInt = myInt;
exports.add = add;
exports.x = x;
/*  Not a pure module */
