// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello");

console.log("x");

console.log(23);

console.log(-23);

console.log(23.0);

console.log(-23.0);

/*  Not a pure module */
