// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var poem = "The boy stood on the burning deck, Whence all but he had fled; The flames that lit the batle\'s wreck... ";

console.log(poem);

console.log("Total harga sebelum diskon: " + (String(15.0) + " "));

console.log("Total harga setelah diskon: " + (String(15.0) + " "));

var total = 15.0;

exports.poem = poem;
exports.total = total;
/*  Not a pure module */
