// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var result = Math.sqrt(Math.abs(-3.75));

var area = Math.PI * 7.0 * 7.0;

console.log(result);

var r = 7.0;

exports.result = result;
exports.r = r;
exports.area = area;
/* result Not a pure module */
