// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function priceIf(size) {
  if (size === /* Small */0) {
    return 11.00;
  } else if (size === /* Medium */1) {
    return 12.50;
  } else if (size === /* Large */2) {
    return 14.00;
  } else {
    return 16.00;
  }
}

console.log(priceIf(/* Medium */1));

console.log(priceIf(/* Large */2));

var mySize = /* Medium */1;

var otherSize = /* Large */2;

var badSize = /* Medium */1;

exports.mySize = mySize;
exports.otherSize = otherSize;
exports.badSize = badSize;
exports.priceIf = priceIf;
/*  Not a pure module */
