// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var total = 7 * 15.5;

console.log("The total price is $", total);

var qty = 7;

var price = 15.5;

exports.qty = qty;
exports.price = price;
exports.total = total;
/*  Not a pure module */
