// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var windChill = 13.12 + 0.6215 * 5.0 - 11.37 * Math.pow(20.0, 0.16) + 0.3965 * 5.0 * Math.pow(20.0, 0.16);

console.log("At temperature " + (String(5.0) + (" degrees C and wind speed " + (String(20.0) + (" km/hr, \n the wind chill temperature is " + (String(windChill) + ""))))));

var t = 5.0;

var v = 20.0;

exports.t = t;
exports.v = v;
exports.windChill = windChill;
/* windChill Not a pure module */
